# -*- coding utf-8 -*-

"""
"""

import unittest
import sys

from adama.tests import TestBaseOrders
from adama.commandment import Commander


class TestCommander(TestBaseOrders):
    """Tests the usage generated by the API for a command
    """

    def setUp(self):
        super(TestCommander, self).setUp()
        self.commander = Commander(self.module, self.command)

    def tearDown(self):
        del self.commander
        super(TestCommander, self).tearDown()

    def test_usage(self):
        assert self.commander.usage() == 'Usage: {0} order [options] [args]'.format(self.command)

    def test_run_not_implemented(self):
        self.assertRaises(NotImplementedError, self.commander, [])

if __name__ == '__main__':
    unittest.main()
