# -*- coding utf-8 -*-

"""
adama.tests.test_commandment
============================

    Testing the commandment API
"""

import unittest

from adama.tests import TestBaseOrders
from adama.commandment import Commander


class TestCommander(TestBaseOrders):
    """Tests the usage generated by the API for a command
    """

    def setUp(self):
        super(TestCommander, self).setUp()
        self.commander = Commander(self.module, self.command)

    def tearDown(self):
        del self.commander
        super(TestCommander, self).tearDown()

    def test_usage(self):
        """Tests the usage of a command
        """
        assert self.commander.usage() == 'Usage: {0} order [options] [args]'\
            .format(self.command)

    def test_run_not_implemented(self):
        """Tests implemented the execute method on commander
        """
        assert self.commander([]) == self.commander.usage()

if __name__ == '__main__':
    unittest.main()
